### ISSUE TITLE
Failed in test_themes.py

### ISSUE THREAD

**Issue by ivanteoh** [getnikola/nikola-themes#103]
When running ``scripts/test_themes.py carpet`` with my new theme (carpet) or any old theme,

I got these error messages,

```
Traceback (most recent call last):
  File "./scripts/test_themes.py", line 97, in <module>
  sanity_check(a)
  File "./scripts/test_themes.py", line 29, in sanity_check
  themes = utils.get_theme_chain(theme, _themes_dir='v7')
TypeError: get_theme_chain() got an unexpected keyword argument '_themes_dir'
```

Any advise on how to resolve this? Thanks.

**Comment by ivanteoh** [comment]
Resolve in https://github.com/getnikola/nikola-themes/pull/104
