### ISSUE TITLE
[mdl] theme use blocks nikola from building

### ISSUE THREAD

**Issue by emilywbailey** [getnikola/nikola-themes#206]
Candidly have not put any effort into debugging this, not a web dev (until today, I guess), & when I saw that the error message ended with a runtime file I went straight to a different theme. Nikola site (`v8.2.0`) currently has all the boilerplate from following the setup wizard + one added page. No other changes.
```
❯ nikola theme -i mdl
[2022-01-16 13:08:47] INFO: theme: Downloading 'https://themes.getnikola.com/v7/mdl.zip'
[2022-01-16 13:08:47] INFO: theme: Extracting 'mdl' into themes/
[2022-01-16 13:08:47] WARNING: theme: This theme has a sample config file.  Integrate it with yours in order to make this theme work!
Contents of the conf.py.sample file:

GLOBAL_CONTEXT = {
    "mdl__version": "1.3.0",
    "mdl__color_scheme": "indigo-pink",
    "mdl__roboto_font": False,
    "mdl__late_load_css": False,
    "mdl__cachebusting": "1",
    "mdl__fixed_header": False,
    "mdl__fixed_drawer": False,
    "mdl__no_drawer_button": False,
    "mdl__no_desktop_drawer_button": False,
    "mdl__multiple_header": False,
    "mdl__header_scroll": False,
    "mdl__header_waterfall": False,
    "mdl__header_waterfall_hide_top": False,
    "mdl__header_transparent": False,
    "mdl__header_seamed": False,
    "mdl__footer": "",
    "mdl__navigation_large_screen_only": False,
    "mdl__drawer_small_screen_only": False,
    "mdl__custom_css": False,
    "mdl__custom_js": False,
NAVIGATION_LINKS = {
    "drawer_title": "",
    "drawer_logo_url": "",
    "drawer_show_title": "",
    "drawer_description": "",
    "drawer_note": "",
    "title_row_middle": False,
    "navigation_row_middle": False,
    "breadcrumb_separator": ">",
    "post_type": {
        "text": "format_align_justify",
    },
    "top_nav_header": False,
    "more_button_header": [
        ("/pages/handbook.html", "Handbook", "Handbook"),
    ],
    "image_plugin": "colorbox",
}
[2022-01-16 13:08:47] INFO: theme: Remember to set THEME="mdl" in conf.py to use this theme.
~/mypath  dev dev
❯ vi conf.py
~/mypath  dev dev
❯ nikola build
Scanning posts........done!
#     (
.  render_taxonomies:output/archive.html
TaskError - taskid:render_taxonomies:output/archive.html
PythonAction Error
Traceback (most recent call last):
  File "/myroot/.pyenv/versions/3.6.11/lib/python3.6/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/myroot/.pyenv/versions/3.6.11/lib/python3.6/site-packages/nikola/nikola.py", line 1488, in render_template
    template_name, None, local_context)
  File "/myroot/.pyenv/versions/3.6.11/lib/python3.6/site-packages/nikola/plugins/template/mako.py", line 118, in render_template
    data = template.render_unicode(**context)
  File "/myroot/.pyenv/versions/3.6.11/lib/python3.6/site-packages/mako/template.py", line 482, in render_unicode
    self, self.callable_, args, data, as_unicode=True
  File "/myroot/.pyenv/versions/3.6.11/lib/python3.6/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/myroot/.pyenv/versions/3.6.11/lib/python3.6/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/myroot/.pyenv/versions/3.6.11/lib/python3.6/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/myroot/mypath/cache/.mako.tmp/base.tmpl.py", line 67, in render_body
    __M_writer(str(base.html_headstart()))
  File "/myroot/mypath/cache/.mako.tmp/base_helper.tmpl.py", line 139, in render_html_headstart
    __M_writer(str(html_stylesheets()))
  File "/.../cache/.mako.tmp/base_helper.tmpl.py", line 59, in html_stylesheets
    return render_html_stylesheets(context)
  File "/myroot/mypath/cache/.mako.tmp/base_helper.tmpl.py", line 282, in render_html_stylesheets
    __M_writer(str(mdl__cachebusting))
  File "/myroot/.pyenv/versions/3.6.11/lib/python3.6/site-packages/mako/runtime.py", line 230, in __str__
    raise NameError("Undefined")
NameError: Undefined

########################################
render_taxonomies:output/archive.html <stdout>:
```

**Comment by emilywbailey** [comment]
`willy-theme` is also giving me trouble, albeit a completely different issue (it builds, just fails to pick up a number of design elements) so maybe I misunderstood these themes to be more plug & go than they actually are. closing the issue until I'm more familiar w/ the intent / how much I'm supposed to know about html/css/mako/jinja/... to use them
