### ISSUE TITLE
bootswatch_theme throws error SSL23_GET_SERVER_HELLO

### ISSUE THREAD

**Issue by timmie** [getnikola/nikola-themes#56]
```
nikola bootswatch_theme -s united united
[2015-09-05T20:50:07Z] WARNING: bootswatch_theme: "bootswatch_theme" only makes sense for themes that use bootstrap
[2015-09-05T20:50:07Z] INFO: bootswatch_theme: Creating 'custom' theme from 'united' and 'bootstrap3'
[2015-09-05T20:50:07Z] INFO: bootswatch_theme: Downloading: https://bootswatch.com/united/bootstrap.min.css
[2015-09-05T20:50:07Z] INFO: requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): bootswatch.com
[2015-09-05T20:50:07Z] WARNING: InsecurePlatformWarning: virtualenvs/nikola/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Traceback (most recent call last):
  File "virtualenvs/nikola/local/lib/python2.7/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "virtualenvs/nikola/local/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "virtualenvs/nikola/local/lib/python2.7/site-packages/nikola/plugin_categories.py", line 127, in execute
    return self._execute(options, args)
  File "virtualenvs/nikola/local/lib/python2.7/site-packages/nikola/plugins/command/bootswatch_theme.py", line 99, in _execute
    data = requests.get(url).text
  File "virtualenvs/nikola/local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "virtualenvs/nikola/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "virtualenvs/nikola/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "virtualenvs/nikola/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "virtualenvs/nikola/local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

```

**Comment by Kwpolska** [comment]
Your SSL is broken, and we are not responsible for this. Please google this error and the name of your distribution/operating system

PS. the correct command is `nikola bootswatch_theme -s united -n united`
