### ISSUE TITLE
Python error building with material-theme

### ISSUE THREAD

**Issue by M42** [getnikola/nikola-themes#91]
I have installed material-theme using `nikola install_theme material-theme`, but when I set the variable `THEME="material-theme"` in the configuration file and try to build, I get the following error:

```
TaskError - taskid:render_archive:output/en/archive.html
PythonAction Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/doit/action.py", line 372, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nikola/nikola.py", line 1037, in render_template
    template_name, None, local_context)
  File "/usr/lib/python2.7/dist-packages/nikola/plugins/template/jinja.py", line 92, in render_template
    output = template.render(**context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "themes/material-theme/templates/list.tmpl", line 2, in top-level template code
    {% extends 'base.tmpl' %}
  File "themes/material-theme/templates/base.tmpl", line 59, in top-level template code
    {% block content %}{% endblock %}
  File "themes/material-theme/templates/list.tmpl", line 12, in block "content"
    {% for text, link, count in items %}
ValueError: need more than 2 values to unpack
```

**Comment by Kwpolska** [comment]
Update Nikola. If you’re using the Debian/Ubuntu package: please remove it and [install in a virtualenv](https://getnikola.com/getting-started.html). You might also want to complain to Debian that they’re still shipping an old version of Nikola.
